package org.fundaciobit.plugins.certificate.afirmacxf.validarcertificadoapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Fri May 02 11:43:21 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://afirmaws/services/ValidarCertificado", name = "Validacion")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Validacion {

    @WebResult(name = "ValidarCertificadoReturn", targetNamespace = "http://afirmaws/services/ValidarCertificado", partName = "ValidarCertificadoReturn")
    @WebMethod(operationName = "ValidarCertificado")
    public java.lang.String validarCertificado(
        @WebParam(partName = "parametrosIn", name = "parametrosIn")
        java.lang.String parametrosIn
    );
}
